[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ffbayes"
version = "0.1.0"
description = "Unified Fantasy Football Analytics Pipeline"
requires-python = ">=3.10"
authors = [{ name = "FFBayes" }]
readme = "README.md"
keywords = ["fantasy-football", "bayesian", "monte-carlo", "pymc", "pipeline"]
license = { text = "MIT" }

[project.optional-dependencies]
dev = ["pytest>=7", "ruff>=0.5", "mypy>=1.5"]

[project.scripts]


[tool.ruff.lint]
select = [
  "E",  # pycodestyle
  "F",  # pyflakes
  "I",  # isort
]
ignore = [
  "F841",  # no unused variable
  "E501",  # line length handled by formatter
]

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = true

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["ffbayes*"]
